services:
  catalogue:
    image: catalogue
    container_name: catalogue
    depends_on: 
    - mongodb
  mongodb:
    image: mongodb
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  user:
    image: user:v1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  payment:
    image: payment:v1
    container_name: payment
    depends_on: 
    - rabbitmq
    - cart
    - user 
  frontend: 
    image: frontend
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - payment
    - shipping

      
networks:
  default:
    driver: bridge
    name: roboshop2
    external: false # true if you have created network manually using docker network command 
  
volumes:
  mongodb: #docker volume create mongodb
  redis:
  mysql:
  rabbitmq:
  

